### ISSUE TITLE
Ich kann kein Profilbild hochladen

### ISSUE THREAD

**Issue by LostInDarkMath** [matchinit-app/matchinit_issues#4]
Ich komme über "Ändern" in den Dateimanager, selektiere dort ein Bild und drücke okay. Dann schließt sich der Dateimanager und es passiert nichts. Ich sehe keinen Upload und kein Bild, sondern weiterhin das Placeholder-Bild.

Xiaomi Mi A2 Lite mit Android 10

**Comment by Pollopiccante** [comment]
Könntest du das Bild oder ein Bild, dass nicht hochläd hier posten ? Dann kann ich probieren es mal hochzuladen.

**Comment by LostInDarkMath** [comment]
![me](https://user-images.githubusercontent.com/32729196/155298283-9d27f632-4775-4d05-abbd-55d20557728a.jpeg)

**Comment by Pollopiccante** [comment]
Ich konnte es erfolgreich hochladen. 
![Screenshot_20220223-123409](https://user-images.githubusercontent.com/45184920/155312124-26b47b08-7d27-4587-8c00-74311ede0255.png)
Ich würde dir nochmal bescheid sagen, nachdem Fehlermeldungen für die Ansicht verfügbar sind.

**Comment by LostInDarkMath** [comment]
Soll ich mal nen Screencast erstellen? Oder mit LogCat die Android-Logs checken?

**Comment by Pollopiccante** [comment]
Eine Version mit Uploadindikator und Fehlermeldungen für zu große Bilder / Fehler im Server ist unterwegs. Denke mal spätestens morgen früh ist geprüft.

**Comment by LostInDarkMath** [comment]
Danke! Dass das Bild zu groß ist, glaube ich nicht. Es ist ja nur ca. 250 kByte groß. Aber selbst im Fehlerfall wäre eine entsprechende Fehlermeldung sehr schön :)

**Comment by Pollopiccante** [comment]
Die neue Version sollte jetzt verfügbar sein, kannst ja mal gucken was jetzt passiert.

**Comment by LostInDarkMath** [comment]
Ja, mit der neuen Version funktioniert es, dankeschön!
