### ISSUE TITLE
Lerngruppen-Matching Bug

### ISSUE THREAD

**Issue by Jobba7** [matchinit-app/matchinit_issues#7]
Wenn man in der Matching Area auf den Lerngruppen-Matching Button geht, kommt ein weißer Bildschirm und es passiert nichts. Man muss die App neu starten um sie wieder zu verwenden.
(Ich bin noch in keinem Kurs eingetragen)

**Comment by de-appist** [comment]
Vielen Dank für die Meldung. Wir schauen es uns an.

**Comment by cut-flee** [comment]
Vielen Dank der Bug sollte jetzt gefixt sein
